# AthenaBuild Configuration

# GitHub Configuration
github:
  # Your GitHub personal access token (classic) or fine-grained token
  # Required scopes: repo (or contents:read for fine-grained)
  token: ""

  # GitHub API URL (change if using GitHub Enterprise)
  api_url: "https://api.github.com"

  # Repository settings
  organization: "your_org"
  repository: "your_repo"
  default_branch: "main"

  # Maps structure
  maps:
    # Root folder where all maps are stored
    root_folder: ""
    # Available map categories (used for organizing maps)
    categories:
      - "Arcade"
      - "CTF"
      - "CTW"
      - "DTC"
      - "DTM"
      - "KOTH"
      - "Mixed"
      - "Nexus"
      - "SkyWars"
      - "TDM"
      - "Walls"

upload:
  # Maximum size of world upload in MB
  max_size: 500

  # File types to ignore during extraction
  ignored_files:
    - ".git"
    - ".gitignore"
    - "README.md"
    - "session.lock"
    - "map.xml"
    - "map.yml"
    - "map.png"
    - "map_banner.png"
